// packages/toolbar/src/Toolbar.tsx
import { merge, omit } from 'lodash';
import React, {
	useCallback,
	useEffect,
	useMemo,
	useState,
	useRef,
} from 'react';
import classnames from 'classnames-es-ts';
import { EngineInterface, isMobile } from 'aomao_engine';
import ToolbarGroup from './group';
import {
	getToolbarDefaultConfig,
	fontFamilyDefaultData,
	fontfamily,
} from './config/toolbar';
import { ButtonProps, DropdownProps, ColorProps, CollapseProps } from './types';
import { CollapseGroupProps } from './collapse/group';
import { CollapseItemProps } from './collapse/item';
import locales from './locales';
import './index.css';

export type ToolbarItemProps =
	| ButtonProps
	| DropdownProps
	| ColorProps
	| CollapseProps;

type GroupItemDataProps = {
	// 分组图标-mobile
	icon?: React.ReactNode;
	// 分组内容-mobile
	content?: React.ReactNode | (() => React.ReactNode);
	// 子项
	items: Array<ToolbarItemProps | string>;
};

export type GroupItemProps =
	| Array<
			| ToolbarItemProps
			| string
			| (Omit<CollapseProps, 'groups'> & {
					groups: Array<
						Omit<CollapseGroupProps, 'items'> & {
							items: Array<
								Omit<CollapseItemProps, 'engine'> | string
							>;
						}
					>;
			  })
	  >
	| GroupItemDataProps;

type GroupProps = Omit<GroupItemDataProps, 'items'> & {
	items: Array<ToolbarItemProps>;
};

export type ToolbarProps = {
	engine: EngineInterface;
	items: GroupItemProps[];
	className?: string;
	popup?: boolean;
};

const Toolbar: React.FC<ToolbarProps> = ({
	engine,
	className,
	popup,
	items = [],
}) => {
	const [data, setData] = useState<Array<GroupProps>>([]);
	//移动端浏览器视图信息
	const toolbarRef = useRef<HTMLDivElement | null>(null);
	const updateTimeoutRef = useRef<NodeJS.Timeout | null>(null);
	const [mobileView, setMobileView] = useState({ top: 0 });
	const caluTimeoutRef = useRef<NodeJS.Timeout | null>(null);
	//计算移动浏览器的视图变化
	const calcuMobileView = () => {
		if (!engine.isFocus() || engine.readonly) return;
		if (caluTimeoutRef.current) clearTimeout(caluTimeoutRef.current);
		caluTimeoutRef.current = setTimeout(() => {
			const rect = toolbarRef.current?.getBoundingClientRect();
			const height = rect?.height || 0;
			setMobileView({
				top:
					global.Math.max(
						document.body.scrollTop,
						document.documentElement.scrollTop,
					) +
					(window.visualViewport.height || 0) -
					height,
			});
		}, 100);
	};

	/**
	 * 更新状态
	 */
	const updateState = useCallback(() => {
		if (isMobile) calcuMobileView();
		const data: Array<GroupProps> = [];
		const defaultConfig = getToolbarDefaultConfig(engine);
		items.forEach((group) => {
			const dataGroup: GroupProps = { items: [] };
			if (!Array.isArray(group)) {
				dataGroup.icon = group.icon;
				dataGroup.content = group.content;

				group = group.items;
			}
			group.forEach((item) => {
				let customItem:
					| ButtonProps
					| DropdownProps
					| ColorProps
					| CollapseProps
					| undefined = undefined;
				if (typeof item === 'string') {
					const defaultItem = defaultConfig.find((config) =>
						item === 'collapse'
							? config.type === item
							: config.type !== 'collapse' &&
							  config.name === item,
					);
					if (defaultItem) customItem = defaultItem;
				} else {
					const defaultItem = defaultConfig.find((config) =>
						item.type === 'collapse'
							? config.type === item.type
							: config.type !== 'collapse' &&
							  config.name === item.name,
					);
					// 解析collapse item 为字符串时
					if (item.type === 'collapse') {
						const customCollapse: CollapseProps = {
							...merge(
								omit({ ...defaultItem }, 'groups'),
								omit({ ...item }, 'groups'),
							),
							groups: [],
						};
						item.groups.forEach((group) => {
							const items: Array<
								Omit<CollapseItemProps, 'engine'>
							> = [];
							group.items.forEach((cItem) => {
								let targetItem = undefined;
								(defaultItem as CollapseProps).groups.some(
									(g) =>
										g.items.some((i) => {
											const isEqual =
												i.name ===
												(typeof cItem === 'string'
													? cItem
													: cItem.name);
											if (isEqual) {
												targetItem = {
													...i,
													...(typeof cItem ===
													'string'
														? {}
														: cItem),
												};
											}
											return isEqual;
										}),
								);
								if (targetItem) items.push(targetItem);
								else if (typeof cItem === 'object')
									items.push(cItem);
							});
							if (items.length > 0) {
								customCollapse.groups.push({
									...omit(group, 'itmes'),
									items,
								});
							}
						});
						customItem =
							customCollapse.groups.length > 0
								? customCollapse
								: undefined;
					} else if (item.type === 'dropdown') {
						customItem = defaultItem
							? merge(
									defaultItem,
									omit({ ...item }, 'type', 'items'),
							  )
							: { ...item };
						(customItem as DropdownProps).items = item.items;
					} else {
						customItem = defaultItem
							? merge(defaultItem, omit({ ...item }, 'type'))
							: { ...item };
					}
				}
				if (customItem) {
					if (customItem.type === 'button') {
						if (customItem.onActive)
							customItem.active = customItem.onActive();
						else if (engine.command.queryEnabled(customItem.name))
							customItem.active = engine.command.queryState(
								customItem.name,
							);
					} else if (customItem.type === 'dropdown') {
						if (customItem.onActive)
							customItem.values = customItem.onActive(
								customItem.items,
							);
						else
							customItem.values = engine.command.queryState(
								customItem.name,
							);
					}
					if (customItem.type !== 'collapse')
						customItem.disabled = customItem.onDisabled
							? customItem.onDisabled()
							: !engine.command.queryEnabled(customItem.name);
					else {
						customItem.groups.forEach((group) =>
							group.items.forEach((item) => {
								item.disabled = item.onDisabled
									? item.onDisabled()
									: !engine.command.queryEnabled(item.name);
							}),
						);
					}
					dataGroup.items.push(customItem);
				}
			});
			if (dataGroup.items.length > 0) data.push(dataGroup);
		});
		setData(data);
	}, [engine, items]);

	useMemo(() => {
		updateState();
	}, [engine, items]);

	const update = () => {
		if (updateTimeoutRef.current) clearTimeout(updateTimeoutRef.current);
		updateTimeoutRef.current = setTimeout(() => {
			updateState();
		}, 100);
	};

	useEffect(() => {
		engine.language.add(locales);
		engine.on('select', update);
		engine.on('change', update);
		engine.on('blur', update);
		engine.on('focus', update);
		let scrollTimer: NodeJS.Timeout;

		const hideMobileToolbar = () => {
			setMobileView({
				top: -120,
			});
			clearTimeout(scrollTimer);
			scrollTimer = setTimeout(() => {
				calcuMobileView();
			}, 200);
		};

		const handleReadonly = () => {
			if (engine.readonly) {
				hideMobileToolbar();
			} else {
				calcuMobileView();
			}
		};

		if (isMobile) {
			engine.on('readonly', handleReadonly);
			engine.on('blur', hideMobileToolbar);
			document.addEventListener('scroll', hideMobileToolbar);
			visualViewport.addEventListener('resize', calcuMobileView);
			visualViewport.addEventListener('scroll', calcuMobileView);
		} else {
			engine.on('readonly', update);
		}

		return () => {
			engine.off('select', update);
			engine.off('change', update);
			engine.off('blur', update);
			engine.off('focus', update);
			if (isMobile) {
				engine.off('readonly', handleReadonly);
				engine.off('blur', hideMobileToolbar);
				document.removeEventListener('scroll', hideMobileToolbar);
				visualViewport.removeEventListener('resize', calcuMobileView);
				visualViewport.removeEventListener('scroll', calcuMobileView);
			} else {
				engine.off('readonly', update);
			}
		};
	}, [engine]);

	const onMouseDown = (
		event: React.MouseEvent<HTMLDivElement, MouseEvent>,
	) => {
		const nodeName = (event.target as Node).nodeName;
		if (nodeName !== 'INPUT' && nodeName !== 'TEXTAREA')
			event.preventDefault();
	};

	return (
		<div
			ref={toolbarRef}
			className={classnames('editor-toolbar', className, {
				'editor-toolbar-mobile': isMobile && !popup,
				'editor-toolbar-popup': popup,
			})}
			style={isMobile ? { top: `${mobileView.top}px` } : {}}
			data-element="ui"
			onMouseDown={onMouseDown}
			onMouseOver={(event) => event.preventDefault()}
			onMouseMove={(event) => event.preventDefault()}
			onContextMenu={(event) => event.preventDefault()}
		>
			<div className="editor-toolbar-content">
				{data.map((group, index) => (
					<ToolbarGroup
						key={index}
						engine={engine}
						popup={popup}
						{...group}
					/>
				))}
			</div>
		</div>
	);
};

export default Toolbar;
export {
	fontFamilyDefaultData,
	fontfamily,
	getToolbarDefaultConfig as getDefaultConfig,
};

// packages/toolbar-vue/src/components/toolbar.vue
<template>
    <div
    ref="toolbarRef"
    :class="['editor-toolbar', className, {'editor-toolbar-mobile': isMobile && !popup,
				'editor-toolbar-popup': popup,}]"
    :style="isMobile ? { top: `${mobileView.top}px` } : {}"
    data-element="ui"
    @mousedown="triggerMouseDown"
    @mouseover="triggerMouseOver"
    @mousemove="triggerMouseMove"
    @contextmenu="triggerContextMenu"
    >
        <div class="editor-toolbar-content">
            <am-group v-for="(group,index) in groups" :key="index" :engine="engine" :popup="popup" v-bind="group" />
        </div>
    </div>
</template>
<script lang="ts">
import { defineComponent, onMounted, onUnmounted, ref, reactive } from 'vue'
import { merge, omit } from 'lodash';
import { isMobile } from 'aomao_engine'
import { ToolbarButtonProps, CollapseItemProps, ToolbarColorProps, ToolbarDropdownProps, GroupDataProps, ToolbarCollapseGroupProps, toolbarProps } from '../types'
import AmGroup from './group.vue'
import locales from '../locales';
import { getToolbarDefaultConfig,
	fontFamilyDefaultData,
	fontfamily, } from '../config'

export default defineComponent({
    name:"am-toolbar",
    components:{
        AmGroup
    },
    props:toolbarProps,

    setup(props){
        let groups = ref<Array<GroupDataProps>>([])
        const update = () => {
            if(isMobile) calcuMobileView()
            const data: Array<GroupDataProps> = [];
            const defaultConfig = getToolbarDefaultConfig(props.engine);
            props.items.forEach(group => {
                const dataGroup: GroupDataProps = { items:[] };
                if(!Array.isArray(group)) {
                    dataGroup.icon = group.icon
                    dataGroup.content = group.content

                    group = group.items
                }
                group.forEach(item => {
                    let customItem:ToolbarButtonProps | ToolbarDropdownProps | ToolbarColorProps | ToolbarCollapseGroupProps | undefined = undefined;
                    if (typeof item === 'string') {
                        const defaultItem = defaultConfig.find(config =>
                            item === 'collapse' ? config.type === item : config.type !== 'collapse' && config.name === item,
                        );
                        if (defaultItem) customItem = defaultItem;
                    } else {
                      const defaultItem = defaultConfig.find(config =>
                          item.type === 'collapse' ? config.type === item.type : config.type !== 'collapse' && config.name === item.name,
                      );
                      // 解析collapse item 为字符串时
                      if(item.type === 'collapse')
                      {
                        const customCollapse: ToolbarCollapseGroupProps = {...(merge(omit({...defaultItem}, "groups"), omit({...item}, "groups"))), groups:[]}
                        item.groups.forEach(group => {
                          const items: Array<Omit<CollapseItemProps, 'engine'>> = []
                          group.items.forEach(cItem => {
                            let targetItem = undefined;
                            (defaultItem as ToolbarCollapseGroupProps).groups.some(g => g.items.some(i => {
                              const isEqual = i.name === (typeof cItem === "string" ? cItem : cItem.name)
                              if(isEqual)
                              {
                                targetItem = {...i, ...(typeof cItem === "string" ? {} : cItem)}
                              }
                              return isEqual
                            }))
                            if(targetItem) items.push(targetItem)
                            else if(typeof cItem === "object") items.push(cItem);
                          })
                          if(items.length > 0) {
                            customCollapse.groups.push({...omit(group, "itmes"), items})
                          }
                        })
                        customItem = customCollapse.groups.length > 0 ? customCollapse : undefined
                      } else if(item.type === "dropdown") {
                        customItem = defaultItem ? merge(defaultItem, omit({ ...item }, 'type', "items")) : { ...item };
                        (customItem as ToolbarDropdownProps).items = item.items
                      } else {
                        customItem = defaultItem ? merge(defaultItem, omit({ ...item }, 'type')) : { ...item };
                      }
                    }
                    if (customItem) {
                        if (customItem.type === 'button') {
                            if (customItem.onActive)
                                customItem.active = customItem.onActive();
                            else if (props.engine.command.queryEnabled(customItem.name))
                                customItem.active = props.engine.command.queryState(
                                    customItem.name,
                                );
                        } else if (customItem.type === 'dropdown') {
                            if (customItem.onActive)
                                customItem.values = customItem.onActive(customItem.items);
                            else customItem.values = props.engine.command.queryState(
                                    customItem.name,
                                );
                        }
                        if (customItem.type !== 'collapse')
                          customItem.disabled = customItem.onDisabled ? customItem.onDisabled() : !props.engine.command.queryEnabled(customItem.name);
                        else {
                          customItem.groups.forEach(group => group.items.forEach((item) => {
                            item.disabled = item.onDisabled ? item.onDisabled() : !props.engine.command.queryEnabled(item.name);
                          }))
                          customItem.disabled = !customItem.groups.some(g => g.items.some(item => !item.disabled))
                        }
                        dataGroup.items.push(customItem);
                    }
                });
                if (dataGroup.items.length > 0) data.push(dataGroup);
            });
            groups.value = data
        }

        //移动端浏览器视图信息
        const toolbarRef = ref<HTMLDivElement | null>(null)
        const caluTimeoutRef = ref<NodeJS.Timeout | null>(null);
        const mobileView = reactive({ top: 0 })
        //计算移动浏览器的视图变化
        const calcuMobileView = () => {
          if(!props.engine.isFocus() || props.engine.readonly) return

          if(caluTimeoutRef.value) clearTimeout(caluTimeoutRef.value as NodeJS.Timeout);
          caluTimeoutRef.value = setTimeout(() => {
            const rect = toolbarRef.value?.getBoundingClientRect()
            const height = rect?.height || 0
            mobileView.top = global.Math.max(document.body.scrollTop, document.documentElement.scrollTop) + (window.visualViewport.height || 0) - height
          }, 100);
        }

        let scrollTimer:NodeJS.Timeout;

        const hideMobileToolbar = () => {
            mobileView.top = -120
            clearTimeout(scrollTimer);
            scrollTimer = setTimeout(() => {
                calcuMobileView()
            }, 200);
        }

        const handleReadonly = () => {
          if(props.engine.readonly) {
            hideMobileToolbar()
          } else {
            calcuMobileView()
          }
        }

        let updateTimer: NodeJS.Timeout;

        const updateByTimeout = () => {
            clearTimeout(updateTimer);
            updateTimer = setTimeout(() => {
                update()
            }, 100);
        }

        onMounted(() => {
            props.engine.language.add(locales)
            props.engine.on("select",updateByTimeout)
            props.engine.on("change",updateByTimeout)
            props.engine.on("blur",updateByTimeout)
            props.engine.on('focus', updateByTimeout)
            if (isMobile) {
              props.engine.on('readonly', handleReadonly)
              props.engine.on('blur', hideMobileToolbar)
              document.addEventListener('scroll', hideMobileToolbar);
              visualViewport.addEventListener('resize', calcuMobileView);
              visualViewport.addEventListener('scroll', calcuMobileView);
            } else {
              props.engine.on('readonly', updateByTimeout);
            }
            updateByTimeout()
        })

        onUnmounted(() => {
            props.engine.off("select",updateByTimeout)
            props.engine.off("change",updateByTimeout)
            props.engine.off('readonly', updateByTimeout);
            props.engine.off("blur",updateByTimeout)
            props.engine.off('focus', updateByTimeout)
            if (isMobile) {
              props.engine.off('readonly', handleReadonly)
              props.engine.off('blur', hideMobileToolbar)
              document.removeEventListener('scroll', hideMobileToolbar);
              visualViewport.removeEventListener('resize', calcuMobileView);
              visualViewport.removeEventListener('scroll', calcuMobileView);
            } else {
              props.engine.off('readonly', updateByTimeout);
            }
        })

        return {
            toolbarRef,
            mobileView,
            isMobile,
            groups
        }
    },
    methods:{
        preventDefault(event:MouseEvent){
            event.preventDefault()
        },
        triggerMouseDown(){

        },
        triggerMouseOver(event:MouseEvent){
            this.preventDefault(event)
        },
        triggerMouseMove(event:MouseEvent){
            this.preventDefault(event)
        },
        triggerContextMenu(event:MouseEvent){
            this.preventDefault(event)
        }
    }
})

export {
  getToolbarDefaultConfig,
	fontFamilyDefaultData,
	fontfamily
}
</script>
<style>
.ant-tooltip .toolbar-tooltip-title {
    font-size: 12px;
    text-align: center;
}

.ant-tooltip .toolbar-tooltip-hotkey {
    font-size: 12px;
    color: rgba(255, 255, 255, 0.85);
    text-align: center;
}

.editor-toolbar {
    position: relative;
    width: 100%;
    padding:0;
    z-index: 200;
    border-top:1px solid rgba(0,0,0,.05);
    border-bottom: 1px solid rgba(0,0,0,.05);
    user-select: none;
}

.editor-toolbar .editor-toolbar-content {
    position: relative;
    flex-direction: row;
    background: transparent;
    text-align: center;
    width: 100%;
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
}

.editor-toolbar.editor-toolbar-mobile,.editor-toolbar.editor-toolbar-popover {
    position: absolute;
    left: 0;
    box-shadow: none;
}

.editor-toolbar.editor-toolbar-popup {
    position: initial;
    box-shadow: none;
    top: 0;
    left: 0;
    border: 0 none;
}

.editor-toolbar-mobile .editor-toolbar-content {
    text-align: left;
    padding: 0 12px;
}

.editor-toolbar-mobile .editor-toolbar-group,.editor-toolbar-popup .editor-toolbar-group {
    border: 0 none;
    padding: 0;
}

.editor-toolbar-popup .editor-toolbar-content {
    text-align: center;
    padding: 0;
}

.editor-toolbar-popover .editor-toolbar {
    position: relative;
    box-shadow: none;
    border: 0 none;
    left: 0;
    top: 0;
    display: flex;
}

.editor-toolbar-popover {
    border-radius: 3px;
    background: transparent;
}

.editor-toolbar-popover .ant-popover-inner {
    border-radius: 3px;
}

.editor-toolbar-popover .ant-popover-inner-content {
    padding: 2px;
}

.am-engine-mobile {
  margin-bottom: 40px;
}
</style>
